+incdir+./rtl
+incdir+./IO
+incdir+./IO/PS2
+incdir+./IO/VGA
+incdir+./edf
+incdir+./board

./editor/ip_stubs.v
./rtl/EXT.v
./rtl/NPC.v
./rtl/PC.v
./rtl/RF.v
./rtl/forward_unit.v
./rtl/hazard_unit.v
./rtl/exception_unit.v
./rtl/SCPU.v
./rtl/alu.v
./rtl/ctrl.v
./rtl/dm_controller.v
./IO/MIO_BUS.v
./edf/SPIO.v
./edf/Multi_8CH32.v
./edf/SSeg7.v
./IO/Enter.v
./IO/clk_div.v
./IO/Counter_3_IO.v
./IO/PS2/PS2KB.v
./IO/PS2/PS2IO.v
./IO/VGA/VGA_Scan.v
./IO/VGA/vga_test_pattern.v
