+incdir+./IO
+incdir+./IO/PS2
+incdir+./IO/VGA
+incdir+./rtl
+incdir+./edf
+incdir+./board

./editor/ip_stubs.v
./edf/SCPU.v
./IO/MIO_BUS.v
./rtl/dm_controller.v
./edf/SPIO.v
./edf/Multi_8CH32.v
./edf/SSeg7.v
./IO/Enter.v
./IO/clk_div.v
./IO/Counter_3_IO.v
./IO/PS2/PS2KB.v
./IO/PS2/PS2IO.v
./IO/VGA/vga_timing.v
./IO/VGA/vga_font_rom.v
./IO/VGA/vga_text_ram.v
./IO/VGA/vga_text_renderer.v
./IO/VGA/vga_top.v
./board/top.v
