+incdir+./rtl
+incdir+./IO
+incdir+./edf
+incdir+./board

./editor/ip_stubs.v
./rtl/EXT.v
./rtl/NPC.v
./rtl/PC.v
./rtl/RF.v
./rtl/forward_unit.v
./rtl/hazard_unit.v
./rtl/SCPU.v
./rtl/alu.v
./rtl/ctrl.v
./rtl/dm_controller.v
./edf/MIO_BUS.V
./edf/SPIO.v
./edf/Multi_8CH32.v
./edf/SSeg7.v
./IO/Enter.v
./IO/clk_div.v
./IO/Counter_3_IO.v
./board/top.v
