+incdir+./rtl
+incdir+./IO
+incdir+./IO/PS2
+incdir+./IO/VGA
+incdir+./board
+incdir+./sim

./sim/board_sim_models.v
./rtl/EXT.v
./rtl/NPC.v
./rtl/PC.v
./rtl/RF.v
./rtl/forward_unit.v
./rtl/hazard_unit.v
./rtl/exception_unit.v
./rtl/SCPU.v
./rtl/alu.v
./rtl/ctrl.v
./rtl/dm_controller.v
./IO/Enter.v
./IO/clk_div.v
./IO/Counter_3_IO.v
./IO/MIO_BUS.v
./IO/game_timer.v
./IO/PS2/PS2KB.v
./IO/PS2/PS2IO.v
./IO/VGA/vga_timing.v
./IO/VGA/vga_font_rom.v
./IO/VGA/vga_text_ram.v
./IO/VGA/vga_text_renderer.v
./IO/VGA/vga_top.v
./board/top.v
./sim/top_board_tb.v
