+incdir+./rtl
+incdir+./IO
+incdir+./board
+incdir+./sim

./sim/board_sim_models.v
./rtl/EXT.v
./rtl/NPC.v
./rtl/PC.v
./rtl/RF.v
./rtl/forward_unit.v
./rtl/hazard_unit.v
./rtl/exception_unit.v
./rtl/SCPU.v
./rtl/alu.v
./rtl/ctrl.v
./rtl/dm_controller.v
./IO/Enter.v
./IO/clk_div.v
./IO/Counter_3_IO.v
./board/top.v
./sim/top_board_tb.v
